apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3d-cluster
spec:
  dnsNames:
    - k3d.localhost.org
  secretName: k3d-cluster
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
